# configure a etherpad server that uses a mysql db (hosted in a separate
# container) as a backend
# 
# This config uses 'named' external volumes for storing the persistent data.
# These are managed with the 'docker volume' command.
etherpad:

    # build its image from the etherpad directory
    build:  etherpad

    # TCP redirection: redirect port 9001 of the local host to the 9001 port of
    # the container
    ports:
        - "9001:9001"

    links:
        # link this container to the mysql container (identified as mysql)
        - mysql:mysql

    volumes:
        # store the var directory into the 'dev-etherpad-var' volume
        - dev-etherpad-var:/opt/etherpad/var

mysql:
    # use the official mariadb image (will be pulled from the docker hub)
    # https://store.docker.com/images/mariadb
    image: mariadb:10

    # container configuration
    environment:
        MYSQL_ROOT_PASSWORD:      very_secret_root
        MYSQL_USER:               etherpad
        MYSQL_PASSWORD:           etherpad
        MYSQL_DATABASE:           etherpad

    volumes:
        # store mysql data into the 'dev-etherpad-db'
        - dev-etherpad-mysql:/var/lib/mysql

# vim:sts=4:sw=4:
