# configure a etherpad server that uses a mysql db (hosted in a separate
# container) as a backend
# 
# This config uses 'named' external volumes for storing the persistent data.
# These are managed with the 'docker volume' command.

version: '2'

networks:
    etherpad_net:
        ipam:
            config:
                - subnet:     "10.123.0.0/24"

volumes:
    dev-etherpad-var:
    dev-etherpad-mysql:

services:

    etherpad:

        # build its image from the etherpad directory
        build:  etherpad

        networks:
            etherpad_net:

        extra_hosts:
            mysql: "10.123.0.48"

        # TCP redirection: redirect port 9001 of the local host to the 9001 port of
        # the container
        ports:
            - "9001:9001"

        volumes:
            # store the var directory into the 'dev-etherpad-var' volume
            - dev-etherpad-var:/opt/etherpad/var

    mysql:
        # build its image from the mysql directory
        build: mysql

        networks:
            etherpad_net:
                ipv4_address: "10.123.0.48"

        # container configuration
        environment:
            # root password of the mysql server
            # NOTE: the container uses this value only when initialising the
            #       db from scratch (othewise it is ignored)
            MYSQL_ROOT_PASSWORD:      very_secret_pass

        volumes:
            # store mysql data into the 'dev-etherpad-db'
            - dev-etherpad-mysql:/var/lib/mysql

# vim:sts=4:sw=4:
