# use the official mariadb image (will be pulled from the docker hub)
# https://store.docker.com/images/mariadb
FROM mariadb:10

# conventions expected by the etherpad container
ENV MYSQL_USER		etherpad
ENV MYSQL_PASSWORD	etherpad
ENV MYSQL_DATABASE	etherpad
